export interface GroupReservation {
  groupReservationId: number
  groupName: string
  defaultAdultCount: number
  defaultYouthCount: number
  defaultKidCount: number
  defaultCodeCount: number
  defaultCustomDietCount: number
  arrivalDate: string
  departureDate: string
  customDietNotes?: string
  notes?: string
}

export interface KitchenPrepList {
  kitchenPrepListId: number
  staffInstructions?: string
}

export interface KitchenPrepListItem {
  kitchenPrepListItemId: number
  mealPeriodType?: 'BREAKFAST' | 'LUNCH' | 'DINNER'
  menuItemName: string
  adultServings: number
  youthServings: number
  kidServings: number
  codeServings: number
  notes?: string
  autoGenerated: boolean
  manuallyAdjusted: boolean
}

export interface EventDay {
  eventDayId: number
  date: string
  notes?: string
  kitchenPrepList?: KitchenPrepList
}

export interface Menu {
  menuId: number
  menuName: string
}

export interface MenuItemSummary {
  menuItemId: number
  menuItemName: string
  displayOrder: number | null
}

export interface MealPeriod {
  mealPeriodId: number
  mealPeriodType: 'BREAKFAST' | 'LUNCH' | 'DINNER'
  menu?: Menu
  eventDay?: { eventDayId: number; date: string }
}

export interface GroupMealAttendance {
  groupMealAttendanceId: number
  adultCount: number
  youthCount: number
  kidCount: number
  codeCount: number
  customDietCount: number
  mealPeriod: {
    mealPeriodId: number
    mealPeriodType: 'BREAKFAST' | 'LUNCH' | 'DINNER'
    eventDay: { eventDayId: number; date: string }
  }
}

export interface DateImpact {
  date: string
  isLastGroup: boolean
  hasMealPlan: boolean
  hasKitchenPrepList: boolean
}

export interface ReservationImpact {
  affectedDates: DateImpact[]
}

export interface DayStatus {
  date: string
  hasEventDay: boolean
  groupCount: number
}

export interface MenuWithItems {
  menuId: number
  menuName: string
  items: MenuItemSummary[]
}

export interface Ingredient {
  ingredientId: number
  ingredientName: string
  unitOfMeasure: string
}

export interface MealPlan {
  mealPlanId: number
  name: string
  startDate: string
  endDate: string
}

export interface AttendingGroup {
  groupReservationId: number
  groupName: string
  arrivalDate: string
  departureDate: string
  defaultAdultCount: number
  defaultYouthCount: number
  defaultKidCount: number
  defaultCodeCount: number
  defaultCustomDietCount: number
  customDietNotes?: string
}

export interface GroupTotals {
  adults: number
  youth: number
  kids: number
  code: number
  customDiet: number
  grandTotal: number
}

export interface EventDaySummary {
  eventDayId: number
  date: string
  breakfastMenuName: string | null
  lunchMenuName: string | null
  dinnerMenuName: string | null
}

export type PurchaseListStatus = 'DRAFT' | 'SHOPPING' | 'COMPLETE' | 'ARCHIVED'

export interface PurchaseList {
  purchaseListId: number
  mealPlanId: number
  generatedAt: string
  notes?: string
  status: PurchaseListStatus
}

export type PurchaseListItemStatus = 'SOURCING' | 'PURCHASED'

export interface PurchaseListItem {
  purchaseListItemId: number
  purchaseListItemName: string
  quantity: number
  uom: string
  notes?: string
  checked: boolean
  ingredientId: number | null
  autoGenerated: boolean | null
  vendor?: string | null
  vendorItemNumber?: string | null
  vendorItemDescription?: string | null
  status?: PurchaseListItemStatus | null
  purchaseOrderNumber?: string | null
}

export interface MealPlanDetail {
  mealPlanId: number
  name: string
  startDate: string
  endDate: string
  attendingGroups: AttendingGroup[]
  totals: GroupTotals
  eventDays: EventDaySummary[]
}

export interface MenuItemRecipeEntry {
  menuItemRecipeId: number
  ingredientId: number
  ingredientName: string
  unitOfMeasure: string
  adultPortion: number
  youthPortion: number
  kidPortion: number
  codePortion: number
  notes?: string
}

export interface GroupAttendanceRow {
  groupName: string
  adultCount: number
  youthCount: number
  kidCount: number
  codeCount: number
  customDietCount: number
  customDietNotes?: string
}

export interface AttendanceTotals {
  adultCount: number
  youthCount: number
  kidCount: number
  codeCount: number
}

export type MealTab = 'groups' | 'meals' | 'kitchen-prep'
