package com.event_meal_manager.domain.purchasing;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "purchase_list_items")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PurchaseListItem {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long purchaseListItemId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "purchase_list_id", nullable = false)
    private PurchaseList purchaseList;

    @Column(nullable = false)
    private String purchaseListItemName;

    @Column(nullable = false)
    private Float quantity;

    @Column(nullable = false)
    private String uom;

    @Column(columnDefinition = "TEXT")
    private String notes;

    @Column(nullable = false)
    @Builder.Default
    private Boolean checked = false;

    private Long ingredientId;

    // Nullable so existing rows survive the schema update; treat null as "unknown/legacy".
    private Boolean autoGenerated;

    // Vendor sourcing — all nullable so existing rows survive the schema update.
    private String vendor;

    private String vendorItemNumber;

    @Column(columnDefinition = "TEXT")
    private String vendorItemDescription;

    @Enumerated(EnumType.STRING)
    private PurchaseListItemStatus status;

    private String purchaseOrderNumber;
}
