package com.event_meal_manager.application.purchasing;

import com.event_meal_manager.domain.catalog.MenuEntry;
import com.event_meal_manager.domain.catalog.MenuItemRecipe;
import com.event_meal_manager.domain.planning.EventDay;
import com.event_meal_manager.domain.planning.MealPeriod;
import com.event_meal_manager.domain.planning.MealPlan;
import com.event_meal_manager.domain.purchasing.PurchaseList;
import com.event_meal_manager.domain.purchasing.PurchaseListItem;
import com.event_meal_manager.domain.purchasing.PurchaseListStatus;
import com.event_meal_manager.domain.reservation.GroupMealAttendance;
import com.event_meal_manager.domain.services.AttendanceTotalsCalculator;
import com.event_meal_manager.domain.services.IngredientAggregationService;
import com.event_meal_manager.domain.services.PortionCalculator;
import com.event_meal_manager.domain.services.PurchaseListBuilder;
import com.event_meal_manager.infrastructure.persistence.planning.EventDayRepository;
import com.event_meal_manager.infrastructure.persistence.planning.MealPlanRepository;
import com.event_meal_manager.infrastructure.persistence.purchasing.PurchaseListItemRepository;
import com.event_meal_manager.infrastructure.persistence.purchasing.PurchaseListRepository;
import com.event_meal_manager.infrastructure.persistence.reservation.GroupMealAttendanceRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class PurchaseListGenerationService {

    private final MealPlanRepository mealPlanRepository;
    private final EventDayRepository eventDayRepository;
    private final PurchaseListRepository purchaseListRepository;
    private final PurchaseListItemRepository purchaseListItemRepository;
    private final GroupMealAttendanceRepository groupMealAttendanceRepository;
    private final PortionCalculator portionCalculator;
    private final IngredientAggregationService ingredientAggregationService;
    private final AttendanceTotalsCalculator attendanceTotalsCalculator;
    private final PurchaseListBuilder purchaseListBuilder;

    /**
     * Ensures a single PurchaseList per MealPlan. If one already exists, its auto-generated
     * items (those linked to an ingredient) are cleared and replaced; custom items are preserved.
     * If none exists, a new one is created and populated.
     */
    @Transactional
    public PurchaseList generateFromMealPlan(Long mealPlanId) {
        MealPlan mealPlan = mealPlanRepository.findById(mealPlanId)
            .orElseThrow(() -> new IllegalArgumentException("MealPlan not found: " + mealPlanId));

        Map<String, IngredientAggregationService.AggregatedIngredient> aggregated =
            aggregateForMealPlan(mealPlan);

        List<PurchaseList> existing = purchaseListRepository.findByMealPlanMealPlanId(mealPlanId);
        PurchaseList purchaseList = existing.isEmpty()
            ? purchaseListBuilder.buildEmpty(mealPlan)
            : existing.get(0);

        // Remove previously auto-generated items; keep custom + catalog-added items.
        // Legacy rows (autoGenerated == null) with an ingredientId are treated as auto-generated.
        purchaseList.getItems().removeIf(item ->
            Boolean.TRUE.equals(item.getAutoGenerated())
            || (item.getAutoGenerated() == null && item.getIngredientId() != null)
        );

        // Append freshly-generated items to the existing list.
        for (IngredientAggregationService.AggregatedIngredient agg : aggregated.values()) {
            PurchaseListItem item = PurchaseListItem.builder()
                .purchaseList(purchaseList)
                .purchaseListItemName(agg.ingredientName())
                .quantity(agg.quantity())
                .uom(agg.uom())
                .ingredientId(agg.ingredientId())
                .checked(false)
                .autoGenerated(true)
                .build();
            purchaseList.getItems().add(item);
        }

        purchaseList.setGeneratedAt(LocalDateTime.now());
        if (purchaseList.getStatus() == null) {
            purchaseList.setStatus(PurchaseListStatus.DRAFT);
        }
        return purchaseListRepository.save(purchaseList);
    }

    @Transactional
    public int clearGeneratedItems(Long purchaseListId) {
        PurchaseList purchaseList = purchaseListRepository.findById(purchaseListId)
            .orElseThrow(() -> new IllegalArgumentException("PurchaseList not found: " + purchaseListId));

        List<PurchaseListItem> toRemove = new ArrayList<>();
        for (PurchaseListItem item : purchaseList.getItems()) {
            boolean isGenerated = Boolean.TRUE.equals(item.getAutoGenerated())
                || (item.getAutoGenerated() == null && item.getIngredientId() != null);
            if (isGenerated) {
                toRemove.add(item);
            }
        }
        purchaseList.getItems().removeAll(toRemove);
        purchaseListRepository.save(purchaseList);
        return toRemove.size();
    }

    private Map<String, IngredientAggregationService.AggregatedIngredient> aggregateForMealPlan(MealPlan mealPlan) {
        Map<String, IngredientAggregationService.AggregatedIngredient> aggregated = new HashMap<>();

        List<EventDay> eventDays = eventDayRepository.findByDateBetween(mealPlan.getStartDate(), mealPlan.getEndDate());
        for (EventDay eventDay : eventDays) {
            for (MealPeriod mealPeriod : eventDay.getMealPeriods()) {
                if (mealPeriod.getMenu() == null) {
                    continue;
                }

                List<GroupMealAttendance> attendances = groupMealAttendanceRepository
                    .findByMealPeriodMealPeriodId(mealPeriod.getMealPeriodId());

                AttendanceTotalsCalculator.AttendanceTotals totals = attendanceTotalsCalculator.calculateTotals(attendances);

                for (MenuEntry menuEntry : mealPeriod.getMenu().getMenuEntries()) {
                    for (MenuItemRecipe recipe : menuEntry.getMenuItem().getRecipes()) {
                        float quantity = portionCalculator.calculateTotalPortion(
                            recipe,
                            totals.adultCount(),
                            totals.youthCount(),
                            totals.kidCount(),
                            totals.codeCount()
                        );

                        aggregated = ingredientAggregationService.aggregateWithId(
                            aggregated,
                            recipe.getIngredient().getIngredientName(),
                            recipe.getIngredient().getUnitOfMeasure(),
                            quantity,
                            recipe.getIngredient().getIngredientId()
                        );
                    }
                }
            }
        }
        return aggregated;
    }

    @Transactional
    public PurchaseList createEmptyForMealPlan(Long mealPlanId) {
        MealPlan mealPlan = mealPlanRepository.findById(mealPlanId)
            .orElseThrow(() -> new IllegalArgumentException("MealPlan not found: " + mealPlanId));

        PurchaseList purchaseList = purchaseListBuilder.buildEmpty(mealPlan);
        return purchaseListRepository.save(purchaseList);
    }
}
