package com.event_meal_manager.presentation.planning;

import com.event_meal_manager.application.planning.KitchenPrepService;
import com.event_meal_manager.domain.planning.KitchenPrepList;
import com.event_meal_manager.domain.planning.KitchenPrepListItem;
import com.event_meal_manager.domain.planning.PrepItemStatus;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/kitchen-prep")
@RequiredArgsConstructor
public class KitchenPrepController {

    private final KitchenPrepService kitchenPrepService;

    @GetMapping("/{id}")
    public ResponseEntity<KitchenPrepList> findById(@PathVariable Long id) {
        return kitchenPrepService.findById(id)
            .map(ResponseEntity::ok)
            .orElse(ResponseEntity.notFound().build());
    }

    @GetMapping("/event-day/{eventDayId}")
    public ResponseEntity<KitchenPrepList> findByEventDayId(@PathVariable Long eventDayId) {
        return kitchenPrepService.findByEventDayId(eventDayId)
            .map(ResponseEntity::ok)
            .orElse(ResponseEntity.notFound().build());
    }

    @PostMapping("/event-day/{eventDayId}")
    public ResponseEntity<KitchenPrepList> createForEventDay(@PathVariable Long eventDayId) {
        KitchenPrepList prepList = kitchenPrepService.createForEventDay(eventDayId);
        return ResponseEntity.status(HttpStatus.CREATED).body(prepList);
    }

    @PatchMapping("/{id}/staff-instructions")
    public ResponseEntity<KitchenPrepList> updateStaffInstructions(@PathVariable Long id, @RequestBody UpdateStaffInstructionsRequest request) {
        KitchenPrepList prepList = kitchenPrepService.updateStaffInstructions(id, request.staffInstructions());
        return ResponseEntity.ok(prepList);
    }

    @GetMapping("/{kitchenPrepListId}/items")
    public List<KitchenPrepListItem> findItems(@PathVariable Long kitchenPrepListId) {
        return kitchenPrepService.findItemsByPrepListId(kitchenPrepListId);
    }

    @PostMapping("/{kitchenPrepListId}/items")
    public ResponseEntity<KitchenPrepListItem> addItem(
            @PathVariable Long kitchenPrepListId,
            @RequestBody AddItemRequest request) {
        KitchenPrepListItem item = kitchenPrepService.addItem(
            kitchenPrepListId,
            request.menuItemName(),
            request.adultServings(),
            request.youthServings(),
            request.kidServings(),
            request.codeServings(),
            request.notes(),
            request.mealPeriodId()
        );
        return ResponseEntity.status(HttpStatus.CREATED).body(item);
    }

    @PatchMapping("/items/{itemId}/status")
    public ResponseEntity<KitchenPrepListItem> updateItemStatus(
            @PathVariable Long itemId,
            @RequestBody UpdateStatusRequest request) {
        KitchenPrepListItem item = kitchenPrepService.updateItemStatus(itemId, request.status());
        return ResponseEntity.ok(item);
    }

    @PutMapping("/items/{itemId}")
    public ResponseEntity<KitchenPrepListItem> updateItem(
            @PathVariable Long itemId,
            @RequestBody UpdateItemRequest request) {
        KitchenPrepListItem item = kitchenPrepService.updateItem(
            itemId,
            request.menuItemName(),
            request.adultServings(),
            request.youthServings(),
            request.kidServings(),
            request.codeServings()
        );
        return ResponseEntity.ok(item);
    }

    @PatchMapping("/items/{itemId}/notes")
    public ResponseEntity<KitchenPrepListItem> updateItemNotes(
            @PathVariable Long itemId,
            @RequestBody UpdateNotesRequest request) {
        KitchenPrepListItem item = kitchenPrepService.updateItemNotes(itemId, request.notes());
        return ResponseEntity.ok(item);
    }

    @DeleteMapping("/items/{itemId}")
    public ResponseEntity<Void> deleteItem(@PathVariable Long itemId) {
        kitchenPrepService.deleteItem(itemId);
        return ResponseEntity.noContent().build();
    }

    @PostMapping("/{id}/generate")
    public ResponseEntity<KitchenPrepList> generateFromEventDay(@PathVariable Long id) {
        KitchenPrepList prepList = kitchenPrepService.generateItemsFromEventDay(id);
        return ResponseEntity.ok(prepList);
    }

    @PostMapping("/{id}/clear-generated")
    public ResponseEntity<Void> clearGeneratedItems(@PathVariable Long id) {
        kitchenPrepService.clearAutoGeneratedItems(id);
        return ResponseEntity.noContent().build();
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deletePrepList(@PathVariable Long id) {
        kitchenPrepService.deletePrepList(id);
        return ResponseEntity.noContent().build();
    }

    public record UpdateStaffInstructionsRequest(String staffInstructions) {}
    public record UpdateNotesRequest(String notes) {}
    public record AddItemRequest(String menuItemName, Integer adultServings, Integer youthServings,
                                  Integer kidServings, Integer codeServings, String notes, Long mealPeriodId) {}
    public record UpdateItemRequest(String menuItemName, Integer adultServings, Integer youthServings,
                                     Integer kidServings, Integer codeServings) {}
    public record UpdateStatusRequest(PrepItemStatus status) {}
}
