package com.event_meal_manager.presentation.purchasing;

import com.event_meal_manager.application.purchasing.PurchaseListService;
import com.event_meal_manager.domain.purchasing.PurchaseListItem;
import com.event_meal_manager.domain.purchasing.PurchaseListItemStatus;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/purchase-list-items")
@RequiredArgsConstructor
public class PurchaseListItemController {

    private final PurchaseListService purchaseListService;

    @GetMapping("/purchase-list/{purchaseListId}")
    public List<PurchaseListItemDTO> findByPurchaseListId(@PathVariable Long purchaseListId) {
        return purchaseListService.findItemsByPurchaseListId(purchaseListId).stream()
            .map(this::toDTO)
            .toList();
    }

    @PostMapping("/purchase-list/{purchaseListId}")
    public ResponseEntity<PurchaseListItemDTO> addItem(
            @PathVariable Long purchaseListId,
            @RequestBody AddItemRequest request) {
        PurchaseListItem item = purchaseListService.addItem(
            purchaseListId,
            request.itemName(),
            request.quantity(),
            request.uom(),
            request.notes(),
            request.ingredientId()
        );
        return ResponseEntity.status(HttpStatus.CREATED).body(toDTO(item));
    }

    @PutMapping("/{itemId}")
    public ResponseEntity<PurchaseListItemDTO> updateItem(
            @PathVariable Long itemId,
            @RequestBody UpdateItemRequest request) {
        PurchaseListItem item = purchaseListService.updateItem(
            itemId,
            request.itemName(),
            request.quantity(),
            request.uom(),
            request.notes(),
            request.vendor(),
            request.vendorItemNumber(),
            request.vendorItemDescription(),
            request.status(),
            request.purchaseOrderNumber(),
            request.purchaseQuantity(),
            request.purchaseUom()
        );
        return ResponseEntity.ok(toDTO(item));
    }

    @PatchMapping("/{itemId}/toggle-checked")
    public ResponseEntity<PurchaseListItemDTO> toggleChecked(@PathVariable Long itemId) {
        PurchaseListItem item = purchaseListService.toggleItemChecked(itemId);
        return ResponseEntity.ok(toDTO(item));
    }

    @DeleteMapping("/{itemId}")
    public ResponseEntity<Void> deleteItem(@PathVariable Long itemId) {
        purchaseListService.deleteItem(itemId);
        return ResponseEntity.noContent().build();
    }

    private PurchaseListItemDTO toDTO(PurchaseListItem i) {
        return new PurchaseListItemDTO(
            i.getPurchaseListItemId(),
            i.getPurchaseListItemName(),
            i.getQuantity(),
            i.getUom(),
            i.getNotes(),
            i.getChecked(),
            i.getIngredientId(),
            i.getAutoGenerated(),
            i.getVendor(),
            i.getVendorItemNumber(),
            i.getVendorItemDescription(),
            i.getStatus(),
            i.getPurchaseOrderNumber(),
            i.getPurchaseQuantity(),
            i.getPurchaseUom()
        );
    }

    public record PurchaseListItemDTO(
        Long purchaseListItemId,
        String purchaseListItemName,
        Float quantity,
        String uom,
        String notes,
        Boolean checked,
        Long ingredientId,
        Boolean autoGenerated,
        String vendor,
        String vendorItemNumber,
        String vendorItemDescription,
        PurchaseListItemStatus status,
        String purchaseOrderNumber,
        Float purchaseQuantity,
        String purchaseUom
    ) {}

    public record AddItemRequest(String itemName, float quantity, String uom, String notes, Long ingredientId) {}
    public record UpdateItemRequest(
        String itemName,
        float quantity,
        String uom,
        String notes,
        String vendor,
        String vendorItemNumber,
        String vendorItemDescription,
        PurchaseListItemStatus status,
        String purchaseOrderNumber,
        Float purchaseQuantity,
        String purchaseUom
    ) {}
}
